### PR TITLE
Trim low policy nodes when node budget is low

### PR DESCRIPTION
**Pull request by WhiteHalmos**

### CODE REVIEW

**Comment by WhiteHalmos** [comment]
Tests were conducted with MAX_NODE_LIMIT set 10,000 times smaller.

**Comment by gcp** [comment]
Seems very reasonable to me. The choice of constants is such that it's unlikely to have a strength regression, even if the search will be different as soon as memory reaches 50% full.

**Comment by gcp** [comment]
Well I did not expect this to happen:

```
./leelaz -w autogtp/networks/1ccb7342725e452e3e5936096a7c527dfca15f122ca616428
02aea619aaa7729 -v 3200 -s 1 -t 1  --benchmark
Thinking at most 2678400.0 seconds...
NN eval=0.537390
Playouts: 2608, Win: 54.06%, PV: D4 C3 D3 C4 C5 B5 B6 C6 D5 B7 B4 A6 B3 C16 Q4 R3 R4 Q3 P3 P2 O2 O3 P4 N2

  D4 ->     713 (V: 54.01%) (N: 22.50%) PV: D4 C3 D3 C4 C5 B5 B6 C6 D5 B7 B4 A6 B3 C16 Q4 R3 R4 Q3 P3 P2 O2 O3 P4 N2
 Q2 O1
  D3 ->     545 (V: 54.52%) (N: 11.21%) PV: D3 D17 Q4 R3 R4 Q3 P3 P2 O2 O3 P4 N2 Q2 O1 R2 C5 R17 R16 Q17 O17 P17
  C4 ->     537 (V: 54.50%) (N: 11.15%) PV: C4 C16 Q4 R3 R4 Q3 P3 P2 O2 O3 P4 N2 Q2 O1 R2 E3 D6 F16 R17 R16 Q17 O17 
P17
  Q4 ->     250 (V: 53.40%) (N: 11.29%) PV: Q4 D3 D16 R3 Q3 R4 R5 S5 S6
 D16 ->     249 (V: 53.44%) (N: 11.00%) PV: D16 C4 Q4 C17 C16 D17 E17 E18 F18 F17
  Q3 ->     234 (V: 54.10%) (N:  6.92%) PV: Q3 D3 D16 C17 D17 C16 C15 B15 B14 C14 D15
  R4 ->     230 (V: 54.05%) (N:  7.10%) PV: R4 D3 D16 C17 D17 C16 C15 B15 B14 C14
 C16 ->     215 (V: 54.03%) (N:  6.73%) PV: C16 C4 Q4 R3 R4 Q3 P3 P2 O2 O3
 D17 ->     212 (V: 54.00%) (N:  6.76%) PV: D17 C4 Q4 R3 R4 Q3 P3 P2 O2
 R17 ->      14 (V: 53.24%) (N:  0.67%) PV: R17 R16 Q17 O17 P17 P16 O18
8.7 average depth, 27 max depth
2549 non leaf nodes, 1.26 average children
3200 visits, 1130633 nodes, 3199 playouts, 1035 n/s
```

```
    static constexpr auto MAX_TREE_SIZE = 100'000
./leelaz -w autogtp/networks/1ccb7342725e452e3e5936096a7c527dfca15f122ca616428
02aea619aaa7729 -v 3200 -s 1 -t 1  --benchmark
Thinking at most 2678400.0 seconds...
NN eval=0.537390
Playouts: 2700, Win: 54.09%, PV: D4 C3 D3 C4 C5 B5 B6 C6 D5 B7 B4 A6 B3 C16 Q4 R3 R4 Q3 P3 P2 O2 O3 P4 N2 Q2

  D4 ->     713 (V: 54.01%) (N: 22.50%) PV: D4 C3 D3 C4 C5 B5 B6 C6 D5 B7 B4 A6 B3 C16 Q4 R3 R4 Q3 P3 P2 O2 O3 P4 N2
 Q2 O1
  D3 ->     545 (V: 54.52%) (N: 11.21%) PV: D3 D17 Q4 R3 R4 Q3 P3 P2 O2 O3 P4 N2 Q2 O1 R2 C5 R17 R16 Q17 O17 P17
  C4 ->     537 (V: 54.50%) (N: 11.15%) PV: C4 C16 Q4 R3 R4 Q3 P3 P2 O2 O3 P4 N2 Q2 O1 R2 E3 D6 F16 R17 R16 Q17 O17 
P17
  Q4 ->     250 (V: 53.40%) (N: 11.29%) PV: Q4 D3 D16 R3 Q3 R4 R5 S5 S6
 D16 ->     249 (V: 53.44%) (N: 11.00%) PV: D16 C4 Q4 C17 C16 D17 E17 E18 F18 F17
  Q3 ->     234 (V: 54.10%) (N:  6.92%) PV: Q3 D3 D16 C17 D17 C16 C15 B15 B14 C14 D15
  R4 ->     230 (V: 54.05%) (N:  7.10%) PV: R4 D3 D16 C17 D17 C16 C15 B15 B14 C14
 C16 ->     215 (V: 54.03%) (N:  6.73%) PV: C16 C4 Q4 R3 R4 Q3 P3 P2 O2 O3
 D17 ->     212 (V: 54.00%) (N:  6.76%) PV: D17 C4 Q4 R3 R4 Q3 P3 P2 O2
 R17 ->      14 (V: 53.24%) (N:  0.67%) PV: R17 R16 Q17 O17 P17 P16 O18
5.1 average depth, 27 max depth
2549 non leaf nodes, 1.26 average children
3200 visits, 68617 nodes, 3199 playouts, 1081 n/s
```

Great! Not pruning the early nodes seems to be very important.

**Comment by killerducky** [comment]
I think this is a good change, just asking to understand: There isn't any mechanism to readd children later? If the game proceeds and the tree is reused, eventually we could get closer to nodes that have been trimmed. Then even the low prior nodes would normally get explored, except they can't because they're gone?

So maybe later we can add a re-expand mechanism?

**Comment by gcp** [comment]
It's indeed an issue, but note that the original test was with games, so it does sortof show that in the end it keeps the program stronger.

I guess the probability that a move that was only added in the >50% tree size part ending up at the root just isn't that big.

**Comment by TFiFiE** [comment]
Can't this be a bit more graceful, with less arbitrary constants? For example:
```
    if (percent > 0.5f) {
        float max_psa = nodelist[0].first;
        min_psa = max_psa * std::exp(percent, EXP);
    }
```
where EXP is fine tuned.

**Pull request merged**
