### PR TITLE
Simplify Im2col for the filter_size = 1 case

### PR DESCRIPTION
**Pull request by sethtroisi**
im2Col is overly complicated*, I'm a proponent of You Ain't Gonna Need It.
let's replaced this potentially buggy code with an assert(filter_size = 1) + copy till a larger filter size is needed at that point this can be reverted or less buggy code written.

*uses many different for loop styles, has a host of extra variables, performs an unsafe signed to unsigned conversion and ultimately doesn't do anything.

### CODE REVIEW

**Comment by gcp** [comment]
Don't let the people in issue #70 hear you.

**Comment by gcp** [comment]
I wonder what makes you say the cast is unsafe. I specifically checked the guarantees for this conversion.

**Comment by gcp** [comment]
Given that im2col is templated on filter size, can't you just add a specialization for == 1 that does the copy?

**Comment by sethtroisi** [comment]
I wrote a version that cleans up what I don't like about the current code. I'll add that to this pull request and then template this for one.

**Comment by sethtroisi** [comment]
Template specialization on functions is complicated: https://stackoverflow.com/a/10695059/459714

**Comment by gcp** [comment]
Your link talks about partial specialization. im2col has only 1 template parameter.

**Comment by sethtroisi** [comment]
Fixed, and implementation looks very clean now :)

Sorry that all my pull requests require extra guidance

**Comment by gcp** [comment]
I pulled the specialization because this looks like the most useful for me.

As for the rest of this pull request: although I don't think providing a full CPU implementation is a priority right now, I also see no need to remove working code and make it harder for anyone who wants to attempt to make one. I took a look at your code review and I disagree on most remarks. In a CPU implementation this code is performance critical, so things like downward counting loops, and avoiding the dual comparison for the row (which is where the cast is used) have measurable performance impact. The code was written this way for a reason!

**Comment by sethtroisi** [comment]
I think the specialization gives an 8% speedup (as measured by 3x50000 netbench tests)

**Comment by gcp** [comment]
Very nice!

**Comment by sethtroisi** [comment]
Can you explain what im2col should do when filter_size > 1?

I've tried my hardest to understand the code, I've tried to do my due diligence but I don't get it,
I really think the current code would generate the wrong result (and I'm super passionate for some reason about fixing it)

**Comment by gcp** [comment]
https://petewarden.com/2015/04/20/why-gemm-is-at-the-heart-of-deep-learning/
https://arxiv.org/pdf/1410.0759.pdf

**Pull request closed without merging**
