### PR TITLE
autogtp: leelaz command line option output

### PR DESCRIPTION
**Pull request by marcocalignano**

### CODE REVIEW

**Comment by marcocalignano** [comment]
The second commit output is something like this: 

`30 game(s) (29 self played and 1 matches) played in 2 hours and 50 minutes = 5 minutes and 41 seconds per game, 948 ms/move, last game took 43 minutes and 3 seconds.
`

**Comment by gcp** [comment]
Not sure about this. Comparing speeds and so on is much easier if everything is in seconds?

**Comment by marcocalignano** [comment]
That is true.

**Comment by marcocalignano** [comment]
Ok so this is what you want.

**Pull request merged**
