### PR TITLE
move rotate_nn_idx in a table

### PR DESCRIPTION
**Pull request by marcocalignano**
Refactored

### CODE REVIEW

**Comment by marcocalignano** [comment]
@sethtroisi Could you test if this commit is beneficial at all?

**Comment by gcp** [comment]
Maybe benchmark with the table data as std::int16_t as well. (Cache use)

**Comment by marcocalignano** [comment]
Here is my profiling with callgrind:

In processor instructions before this patch
`1,063,013,536  /home/marcuzzo/workspace/leela-zero/src/Network.cpp:Network::get_scored_moves_internal(GameState const*, std::vector<std::bitset<361ul>, std::allocator<std::bitset<361ul> > >&, int) [/home/marcuzzo/workspace/leela-zero/build/leelaz]`

and after 

`305,534,110  /home/marcuzzo/workspace/leela-zero/src/Network.cpp:Network::get_scored_moves_internal(GameState const*, std::vector<std::bitset<361ul>, std::allocator<std::bitset<361ul> > >&, int) [/home/marcuzzo/workspace/leela-zero/build/leelaz]
`

**Comment by marcocalignano** [comment]
After with std::int16_t 

318,681,706  /home/marcuzzo/workspace/leela-zero/src/Network.cpp:Network::get_scored_moves_internal(GameState const*, std::vector<std::bitset<361ul>, std::allocator<std::bitset<361ul> > >&, int) [/home/marcuzzo/workspace/leela-zero/build/leelaz]

**Comment by marcocalignano** [comment]
@gcp How do you want to go on with this patch?

**Comment by marcocalignano** [comment]
@sethtroisi Did you have time to check this PR?

**Pull request merged**
