### PR TITLE
Fix boost package reference for VS2017 build.

### PR DESCRIPTION
**Pull request by kuba97531**

### CODE REVIEW

**Comment by AncalagonX** [comment]
This simple fix to the VS2017 project files allows us to build again in Visual Studio 2017. It worked perfectly for me and fixed [the problem introduced in PR 1618.](https://github.com/gcp/leela-zero/pull/1618#issuecomment-419029732)

**Comment by infinity0** [comment]
You keep making comments like "the problem introduced in PR 1618" - let me make it clear, the problem wasn't introduced "in [that] PR", but by Microsoft's shitty design of VS2017 requiring these sorts of pointless manual hoop-jumping exercises in the first place. I don't use VS2017 or have Windows, there is no chance in hell I or any other contributor without Windows can maintain these files.

**Comment by ChinChangYang** [comment]
To make non-Visual-Studio developer can detect issues on Visual Studio, is it possible to make an auto-build for Visual Studio in Github app, such as appveyor?

In appveyor.yml, it seems the auto-build is already there for VS2017. I am not sure why it did not detect this issue in the PR 1618.

**Comment by infinity0** [comment]
And what would the point of that be? So appveyor fails for all contributors that don't have Windows, so nobody can contribute?

Ideally those files would just be deleted from git and people should know how to autogenerate them locally. You could add a shell script to do that for example.

**Comment by ChinChangYang** [comment]
@infinity0 It is not your fault because appveyor.yml passed. Now we have to root the cause of VS2017 issue. Why appveyor passed, but VS2017 developers still find issues?

**Comment by infinity0** [comment]
As you can read on #1816 I spent a lot of time doing Windows work there, and I agree Windows support is vital.

What I think is bad, is to blame non-Windows contributors for not doing something that can only be done on Windows. If you have VS2017 I suspect it's a simple "cmake" command to generate the right files, it makes no sense to make non-subtle digs at me for "breaking" stuff that only Windows users of VS2017 are in a position to maintain and fix.

**Comment by AncalagonX** [comment]
Hi @infinity0, I definitely wasn't making any digs at you or anybody else and I'm sorry if anything I said seemed like it. You spent a lot of time and effort to contribute #1618 to the LZ project and jumped through a number of hoops to get it accepted. The changes you made were completely above my head, as I'm only a hobbyist programmer with no real CS background—I was just reporting that it affected my ability to build on VS2017.

When I saw this new PR pop up, I went and tested it in combination with your PR and was able to build again. I posted here just to confirm that this PR indeed fixes the boost error I got earlier during building, and that it works on more computers than just the submitter's (kuba97531). I hope that makes sense and everything's cool now.

**Comment by infinity0** [comment]
@kuba97531 no worries, I should have been clear I was referring to @AncalagonX 's multiple comments, both here as well as other issues.

@AncalagonX Your comments contained a lot of redundant information that was easily interpreted as coming from an over-demanding user. For example "this simple fix". Everyone knew it would be simple, but it could only be done by a VS2017 user. In fact on an earlier issue gcp already explained the problem but you seem not to have understood the explanation.

Generally, if you don't understand what the problem is, you should first understand it before making redundant comments on an open source project. For users who don't want to spend the time and effort understanding development issues, there are binary executables on the [releases page](https://github.com/gcp/leela-zero/releases) unaffected by development hiccups like this.

**Comment by AncalagonX** [comment]
I agree with your sentiment, but the exclusionary tone of voice isn't appropriate for an OSS project which relies on the generous contributions of hundreds of individuals, many of which are active on Github whether submitting PRs, participating in discussions, or sending bug reports.

Others can decide whether a short comment + workaround posted [on an issue](https://github.com/gcp/leela-zero/issues/1808#issuecomment-419063817), a single report [on PR #1618](https://github.com/gcp/leela-zero/pull/1618#issuecomment-419029732), and a short review at the top of this current PR was excessive or in any way constituted an attack on the PR you contributed.

We ought to be cautious about how we talk to people so that we don't inadvertently end up scaring away or alienating people from our community. I don't want anyone to feel like their contributions are being discredited, and that was my number one concern when I wrote my message to you above.

**Comment by AncalagonX** [comment]
@infinity0 I agree with your sentiment, but the exclusionary tone of voice isn't appropriate for an OSS project which relies on the generous contributions of hundreds of individuals, many of which are active on Github whether submitting PRs, participating in discussions, or sending bug reports.

Others can decide whether a short comment + workaround posted [on an issue](https://github.com/gcp/leela-zero/issues/1808#issuecomment-419063817), a single report [on PR #1618](https://github.com/gcp/leela-zero/pull/1618#issuecomment-419029732), and a short review at the top of this current PR was excessive or in any way constituted an attack on the PR you contributed.

We ought to be cautious about how we talk to people so that we don't inadvertently end up scaring away or alienating people from our community. I don't want anyone to feel like their contributions are being discredited, and that was my number one concern when I wrote my message to you above.

**Pull request merged**
