### PR TITLE
Unit test framework with Google Test

### LINKED ISSUE #218: Intruducing cppunit?
In my previous work I suspect the GTP command "printsgf" is not working in Windows MSVC compile.

As it will takes a while to run autogtp, finish a game and finally jump into the suspected code, it would be easier if we have a standard test facility like cppunit in hand (and have proper test codes written).

I can add some hack on the code (a new "test" argument to autogtp for example), However in the long term, a unit test facility would be definitely required.

Shall we start working on creating a unit test project?

### PR DESCRIPTION
**Pull request by bood**
Attempt to fix #218 

Tested on `Mac` and `Ubuntu 16 + clang 4.0`. Still working on a Travis integration, but lack of supporting of ubuntu 16 really sucks, may end up with osx. For windows support, we need Appveyor integration, but I don't have a windows machine, so maybe someone else can work on it.

You probably need to run `git submodule update --init --recursive` first to pull the gtest submodule.

On Mac, just run
```
cmake CMakeLists.txt
make tests
./tests
```

For ubuntu, I cannot get it run with gcc, you probably need to specify the compiler with something like below:
```
sudo apt install clang-4.0 lldb-4.0
cmake -DCMAKE_CXX_COMPILER="clang++-4.0" CMakeLists.txt
```

gcc (tried both 5 and 6) is complaining some link error to vector for gtest library, maybe someone else could take a look @gcp @killerducky @sethtroisi ?

### CODE REVIEW

**Comment by bood** [comment]
And I don't know how to resolve the conflict issue, probably `next` did a rebase again? What should I do to resolve?

**Comment by sethtroisi** [comment]
git pull
git checkout <this repo> -- autogtp/Management.cpp autogtp/Management.h
git commit -a

**Comment by bood** [comment]
I think my merge is broken... :-(

**Comment by sethtroisi** [comment]
give me a second to test a command but I'm here to help

**Comment by sethtroisi** [comment]
git checkout bfc5d467f -- autogtp/Management.cpp autogtp/Management.h
git commit -am 'fixed merge with next'

**Comment by bood** [comment]
Never mind, I'll use a new branch to do the PR and cherry pick my related commits

**Pull request closed without merging**
