### PR TITLE
Require --noponder for --visits

### PR DESCRIPTION
**Pull request by WhiteHalmos**
This matches behaviour for --playouts.

### CODE REVIEW

**Comment by CamWagner** [comment]
This is fixed by https://github.com/gcp/leela-zero/pull/1009

**Comment by roy7** [comment]
I sort of thought --visits working with pondering was a feature, not a bug.

**Comment by CamWagner** [comment]
Same. I really like it, it makes responses much quicker.

**Comment by WhiteHalmos** [comment]
If it's a feature, please close the PR.

I thought --visits and --playouts didn't have different meanings other than limiting strength by a different metric.

**Comment by gcp** [comment]
--visits has a sensible meaning with pondering enabled, playouts does not really, so the behavior is intended.

**Comment by WhiteHalmos** [comment]
Ah, with pondering enabled, --visits can end much earlier when it is the bot's turn. Makes sense now.

**Pull request closed without merging**
