### PR TITLE
Add cpplint to CI

### PR DESCRIPTION
**Pull request by MKolman**
# Add cpplint.py
Google's script `cpplint.py` was added to `scripts` folder. It's purpose is finding style errors in C++ code.

# Travis stages
Travis.yml was rewritten to include multiple stages. Currently there are two: test and style

# Running cpplint
You can run linter on any file by using:
```python2 scripts/cpplint.py <path/to/cpp/file>```
The `--filter` argument can disable individual error reporting.

# CI
There are currently 6375 errors (32 unique) in the codebase. By disabling errors that appear in the codebase the cpplint can be included in the CI process. This ensures that new errors are not introduced.

# Input
Please comment if there are some files you do not wish to include in the linting.

# Future TODO:
1. separate test stage into compile and test stages,
1. make proper use of `docker run`,
1. remove single error from ignored errors and fix all occurrences,
1. repeat 3. until all errors are gone.

### CODE REVIEW

**Comment by MKolman** [comment]
Error breakdown:

| Error name | # of occurrences  |
|------|---|
| build/c++11 | 79 |
| build/header_guard | 4 |
| build/include | 44 |
| build/include_order | 162 |
| build/include_what_you_use | 33 |
| build/namespaces | 14 |
| legal/copyright | 5 |
| readability/braces | 24 |
| readability/casting | 71 |
| readability/fn_size | 1 |
| readability/multiline_comment | 3 |
| readability/namespace | 10 |
| readability/todo | 1 |
| runtime/explicit | 23 |
| runtime/indentation_namespace | 37 |
| runtime/int | 36 |
| runtime/references | 106 |
| whitespace/blank_line | 49 |
| whitespace/braces | 700 |
| whitespace/comma | 120 |
| whitespace/comments | 288 |
| whitespace/empty_loop_body | 2 |
| whitespace/end_of_line | 514 |
| whitespace/ending_newline | 2 |
| whitespace/forcolon | 4 |
| whitespace/indent | 181 |
| whitespace/line_length | 913 |
| whitespace/newline | 29 |
| whitespace/operators | 102 |
| whitespace/parens | 169 |
| whitespace/semicolon | 7 |
| whitespace/tab | 2642 |

**Comment by MKolman** [comment]
Do you agree with the selection
All files ending in `.cpp`, `.h` or `.hpp` excluding the following directories:
* ./gtest/
* ./src/half/
* ./src/CL/

Files in folders `clblast_level3` and `clblast_level3_half` have `.clblast` file endings and are therefore not checked.
The following command wil be used:
```
find . -regex ".*\.\(cpp\|h\|hpp\)" -not -path "./gtest/*" -not -path "./src/half" -not -path "./src/CL"
```

This reduces the number of errors down to 874 (30 unique):

| name | # |
|------|---|
| build/c++11 | 26 |
| build/header_guard | 0 |
| build/include | 44 |
| build/include_order | 162 |
| build/include_what_you_use | 32 |
| build/namespaces | 14 |
| legal/copyright | 5 |
| readability/braces | 4 |
| readability/casting | 20 |
| readability/fn_size | 1 |
| readability/multiline_comment | 0 |
| readability/namespace | 3 |
| readability/todo | 1 |
| runtime/explicit | 16 |
| runtime/indentation_namespace | 2 |
| runtime/int | 12 |
| runtime/references | 77 |
| whitespace/blank_line | 9 |
| whitespace/braces | 44 |
| whitespace/comma | 21 |
| whitespace/comments | 37 |
| whitespace/empty_loop_body | 2 |
| whitespace/end_of_line | 19 |
| whitespace/ending_newline | 2 |
| whitespace/forcolon | 4 |
| whitespace/indent | 110 |
| whitespace/line_length | 117 |
| whitespace/newline | 1 |
| whitespace/operators | 2 |
| whitespace/parens | 81 |
| whitespace/semicolon | 5 |
| whitespace/tab | 1 |

**Comment by gcp** [comment]
Can we nail and enable these in this patch?

whitespace/newline | 1
whitespace/tab | 1
whitespace/operators | 2
whitespace/ending_newline | 2
whitespace/forcolon | 4


Maybe this one too:
whitespace/end_of_line | 19

**Comment by gcp** [comment]
>in this patch?

I should probably say: in this pull. i.e. fix in one patch, enable CI lint in the other.

**Pull request merged**
