### PR TITLE
Change visits from int to uint64

### PR DESCRIPTION
**Pull request by GeneralZero**
When running the program for a long time I got "assert(best != nullptr);" for uct_select_child. It took a while to pin point the error but what happened is the number of visits went over the max 32bit int value. 

This creates a large negative value for for the selection value.

This edit change the visits in the UCTNode.* and the TTable.* files.

### CODE REVIEW

**Comment by sethtroisi** [comment]
all pull requests are merged into 'next' branch.

in 'next' typedef for uint64 was removed so it will need to be replaced with 'std::uint64_t'

**Comment by gcp** [comment]
This code doesn't work because of things like:

"auto pick = Random::get_Rng().randuint32()"

Additionally a sanity check for computations that are cast to float is needed, and/or accumulating visits (much of those should already be using double, but maybe not all).

**Comment by gcp** [comment]
To fix that random call you can probably use the C++ standard library to get a correctly generated 64-bit sized int and use the fact that Random confirms to the UniformRandomBitGenerator interface (as IIRC dirichlet_noise already does).

**Comment by gcp** [comment]
I'll close this now. Feel free to reopen if you get a more complete fix.

**Pull request closed without merging**
