### PR TITLE
Add command line option to keep self-play .sgf files

### LINKED ISSUE #68: Running autogtp doesn't save .sgf files
I ran autogtp (v0.4) for a while on my Windows machine. The console prints the individual moves and after a game ends, mentions the dumping and sending the file to the server. However, this file is nowhere to be found - I assume the script automatically removes it or it's only in-memory.

It would be great to see the actual .sgf files accumulating in a folder, to be able to take a look at what kind of games are produced during the training.

### PR DESCRIPTION
**Pull request by tux3**
Can be enabled with -k, or --keep-sgf.
Also adds simple Qt-provided help and version options.

Fix #68

### CODE REVIEW

**Comment by killerducky** [comment]
Maybe it should keep the data file also, not just the sgf?

**Comment by gcp** [comment]
The server code should be resilient against this (we detected duplicate/resubmitted games). But yes, it seems like a good idea to dump into a separate directory. @tux3 can you change this?

**Comment by tux3** [comment]
Sure, I'll make the output path an option and copy uncompressed files then. Unless you'd rather just have it dump into ./sgf/ or something.

**Comment by tux3** [comment]
I added the change and rebased on next, tell me if it looks good!

**Pull request merged**
