### PR TITLE
Deeper ponder

### PR DESCRIPTION
**Pull request by Cabu**
Allow deeper pondering throught the parameter --ponder N
-1: like --noponder
0: Infinite pondering like without specifying Visits and Playouts
1: (Default) Respect Visits and Playouts
N: Multiply Visits and Playouts by N while pondering

### CODE REVIEW

**Comment by Cabu** [comment]
My use case is to limit the programe through --visits and --playout to have it play 'quickly'. But I still like it to use all the time it could (infinite pondering) while I play.

**Comment by gcp** [comment]
>to have it play 'quickly'

Use time_settings.

**Comment by Cabu** [comment]
Even if I set time_settings at the beginning of a games session, it is overridden by OGS and KGS servers at the beginning of each game. As a result time_settings could solve my problem but doesn't :(

**Comment by gcp** [comment]
Then file a bug against the OGS and KGS interfaces? Adding these options to LZ seems senseless.

**Comment by Cabu** [comment]
Setting the time_settings is part of the definition of a new game. How should the engine know how much time it have to play a game if not by using time_settings/kgs-time>_settings ? It is not a OGS/KGS bug, but part of the GTP protocol when starting a new game.

**Comment by gcp** [comment]
> How should the engine know how much time it have to play a game if not by using time_settings/kgs-time>_settings ?

It shouldn't, that's what that command is for, which is what I'm saying: if you want it to play fast, set a fast timecontrol.

**Comment by WhiteHalmos** [comment]
@Cabu you can always keep local modifications specific to KGS and OGS.

**Pull request closed without merging**
