### PR TITLE
Packaging improvements

### PR DESCRIPTION
**Pull request by infinity0**
In preparation for uploading this to Debian, I had to tweak a few things relating to installation.

### CODE REVIEW

**Comment by ChinChangYang** [comment]
Can you describe more about how to set ${CMAKE_INSTALL_BINDIR} when building by cmake or make?

**Comment by gcp** [comment]
Validation can handle other engines than just leelaz, though.

**Comment by ChinChangYang** [comment]
@infinity0 There is already some works on making Debian package in the “next” branch. See https://github.com/gcp/leela-zero/pull/1445 for reference.

I suggest you to make a new branch from “next” branch, not master.

**Comment by gcp** [comment]
>I suggest you to make a new branch from “next” branch, not master.

Yes, please! I didn't notice that.

**Pull request closed without merging**
