### PR TITLE
Correct weight create order in tfprocess.

### PR DESCRIPTION
**Pull request by ywrt**
The txt model file is sensitive to the order in which these are created.

### CODE REVIEW

**Comment by gcp** [comment]
How does this relate to:

https://github.com/gcp/leela-zero/pull/1078#issuecomment-375632463

**Comment by ywrt** [comment]
#1078 changes net_to_model.py to use the right calling convention for TFProcess.
#1088 fix TFProcess to construct network weights in the order that matches leelaz model txt files.

As in, you want both of these changes for net_to_model.py to work correctly.

**Comment by ywrt** [comment]
More specifically: #1078 pulled in https://github.com/gcp/leela-zero/pull/1088/commits/767d58627c1e5ec116b38ad31f801a96d1228d22
#1088 includes that and will also pull in https://github.com/gcp/leela-zero/pull/1088/commits/e2af76a04a651603e31e551d2d2ed65051b29998 to fix the error you reported on #1078, and https://github.com/gcp/leela-zero/pull/1088/commits/fc68809c37d6a040ed2a897b8517a37e65ae3a31 to add a unit-test to cover that error.

Does that answer your question?

**Comment by gcp** [comment]
This now has conflicts with the rebased training_v2 branch, which itself won't properly rebase onto next, ugggh.

If you manage to locally rebase your training changes onto next, it's going to be better to make a new pull out of that and drop the training_v2 branch. I was hoping to use that to pull in some fixes quickly and merge, but because there's now new training stuff arriving in next too, that didn't help.

**Comment by ywrt** [comment]
I'll do the local rebase. It'll probably be ~10-12 hours away though.

**Comment by gcp** [comment]
I assume this was included in https://github.com/gcp/leela-zero/commit/7f8ff149a95be51871b6329786cde8013ae73a37

**Comment by ywrt** [comment]
yes.

**Pull request closed without merging**
