### PR TITLE
Add per-net resign analysis

### PR DESCRIPTION
**Pull request by WhiteHalmos**
Add -n argument for prefixes of network names to analyze. This allows
more fine grained analysis of resign percents on a per-net basis, and
it can be used to analyze groups of networks as well.

Also broke up long lines.

### CODE REVIEW

**Comment by WhiteHalmos** [comment]
Also use one dash for args. Example:
```
gunzip build/sgf/*.gz; scripts/resign_analysis/resign_analysis.py build/sgf/*.debug.txt.0 -r 0.2,0.15,0.1 -n 85c6
gzip: build/sgf/*.gz: No such file or directory
Analyzing networks starting with: 85c6
Resign rate: 0.20 - Black won 20/53 (37.74%)
Black wins - Wrong: 3/20 (15.00%) Correct: 17/20 (85.00%) No Resign: 0/20 (0.00%)
Black wins - Average game length: 104/307 (30705.99% reduction)
White wins - Wrong: 1/33 (3.03%) Correct: 32/33 (96.97%) No Resign: 0/33 (0.00%)
White wins - Average game length: 114/321 (32097.67% reduction)
Overall    - Wrong: 4/53 (7.55%) Correct: 49/53 (92.45%) No Resign: 0/53 (0.00%)
Overall    - Average game length: 110/316 (31572.49% reduction)

Resign rate: 0.15 - Black won 20/53 (37.74%)
Black wins - Wrong: 2/20 (10.00%) Correct: 18/20 (90.00%) No Resign: 0/20 (0.00%)
Black wins - Average game length: 141/307 (30694.03% reduction)
White wins - Wrong: 1/33 (3.03%) Correct: 32/33 (96.97%) No Resign: 0/33 (0.00%)
White wins - Average game length: 137/321 (32090.41% reduction)
Overall    - Wrong: 3/53 (5.66%) Correct: 50/53 (94.34%) No Resign: 0/53 (0.00%)
Overall    - Average game length: 139/316 (31563.50% reduction)

Resign rate: 0.10 - Black won 20/53 (37.74%)
Black wins - Wrong: 0/20 (0.00%) Correct: 20/20 (100.00%) No Resign: 0/20 (0.00%)
Black wins - Average game length: 185/307 (30679.82% reduction)
White wins - Wrong: 1/33 (3.03%) Correct: 32/33 (96.97%) No Resign: 0/33 (0.00%)
White wins - Average game length: 174/321 (32079.03% reduction)
Overall    - Wrong: 1/53 (1.89%) Correct: 52/53 (98.11%) No Resign: 0/53 (0.00%)
Overall    - Average game length: 178/316 (31551.09% reduction)
```
```
gunzip build/sgf/*.gz; scripts/resign_analysis/resign_analysis.py build/sgf/*.debug.txt.0 -r 0.2,0.15,0.1 -n 85c6 -n 1ccb
gzip: build/sgf/*.gz: No such file or directory
Analyzing networks starting with: 1ccb
Resign rate: 0.20 - Black won 138/290 (47.59%)
Black wins - Wrong: 15/138 (10.87%) Correct: 123/138 (89.13%) No Resign: 0/138 (0.00%)
Black wins - Average game length: 147/322 (32157.12% reduction)
White wins - Wrong: 6/152 (3.95%) Correct: 146/152 (96.05%) No Resign: 0/152 (0.00%)
White wins - Average game length: 133/321 (32087.95% reduction)
Overall    - Wrong: 21/290 (7.24%) Correct: 269/290 (92.76%) No Resign: 0/290 (0.00%)
Overall    - Average game length: 140/321 (32120.87% reduction)

Resign rate: 0.15 - Black won 138/290 (47.59%)
Black wins - Wrong: 8/138 (5.80%) Correct: 130/138 (94.20%) No Resign: 0/138 (0.00%)
Black wins - Average game length: 170/322 (32149.87% reduction)
White wins - Wrong: 5/152 (3.29%) Correct: 146/152 (96.05%) No Resign: 1/152 (0.66%)
White wins - Average game length: 162/321 (32079.16% reduction)
Overall    - Wrong: 13/290 (4.48%) Correct: 276/290 (95.17%) No Resign: 1/290 (0.34%)
Overall    - Average game length: 166/321 (32112.81% reduction)

Resign rate: 0.10 - Black won 138/290 (47.59%)
Black wins - Wrong: 5/138 (3.62%) Correct: 132/138 (95.65%) No Resign: 1/138 (0.72%)
Black wins - Average game length: 193/322 (32142.82% reduction)
White wins - Wrong: 3/152 (1.97%) Correct: 148/152 (97.37%) No Resign: 1/152 (0.66%)
White wins - Average game length: 184/321 (32072.25% reduction)
Overall    - Wrong: 8/290 (2.76%) Correct: 280/290 (96.55%) No Resign: 2/290 (0.69%)
Overall    - Average game length: 188/321 (32105.83% reduction)
```

**Comment by WhiteHalmos** [comment]
Friendly ping @killerducky for review.

**Comment by killerducky** [comment]
I guess python3 doesn't require doing e.g. 1.0*a/b like python2 does?

Looks good to me.

**Comment by WhiteHalmos** [comment]
Nope, all thanks to https://www.python.org/dev/peps/pep-0238/

Resulted in quite the uproar when it was changed. Thanks for the review!

**Pull request merged**
