### PR TITLE
Training pipeline changed to support fp16 based training

### PR DESCRIPTION
**Pull request by ihavnoid**
See issue #330 for relevant discussion.   Reworked patch.

See dtype on main function for changing to float16 training.  Performance difference was not tested as I don't have a decent GPU with good fp16 support, though.

### CODE REVIEW

**Comment by ihavnoid** [comment]
One thing to beware is that this cannot use the old model data dumps (even if we run fp32) because there is a change of variable scope naming.  Probably we won't want to merge as-is, but this is to figure out what else we want to do (or not).

**Comment by gcp** [comment]
At some point I want to fix the weight format (dump the redundant convolution bias weights, and add a bias/translate layer after the batch-norm one). I guess at that point this could be pulled, but not during a run as that would cause quite some headache.

**Comment by gcp** [comment]
Going to close this as it would need to be rebased to all recent training pipeline changes.

**Comment by gcp** [comment]
>One thing to beware is that this cannot use the old model data dumps (even if we run fp32) because there is a change of variable scope naming.

FWIW, as long as net_to_model works, I believe that's a non-issue.

**Pull request closed without merging**
