### PR TITLE
New AutoGTP with multigame support 

### PR DESCRIPTION
**Pull request by marcocalignano**
Please merge before i get new conflicts!

### CODE REVIEW

**Comment by marcocalignano** [comment]
Opps I think there is an error in the licence header of Game.cpp

**Comment by gcp** [comment]
It doesn't compile either :) I'll fix and clean it up. Warning: force-pushes to next branch incoming.

**Comment by marcocalignano** [comment]
here compiles fine what is your problem?

**Comment by gcp** [comment]
std::tuple has an explicit constructor, so your changes to the minimum version aren't legal, see e.g.: https://stackoverflow.com/questions/32084706/why-initialization-doesnt-work-for-tuple

I guess some compilers might accept it nevertheless.

**Comment by marcocalignano** [comment]
ok so my compiler accept and the right sintax is without the '=' ?

**Comment by gcp** [comment]
Yes. I already fixed it, will force-push the next branch a few times with some style fixups too.

**Comment by marcocalignano** [comment]
ok when you are finished I do the same on my Fork so we are on the same page for the next developmen :)

**Comment by gcp** [comment]
./autogtp  -g 4 -k games

Game has ended.
Score: B+353.5
Winner: black

Game has ended.
Score: B+353.5
Winner: black

Game has ended.
Score: B+353.5
Winner: black

Game has ended.
Score: B+353.5
Winner: black

**Comment by gcp** [comment]
The games also look fairly short on average.

**Comment by gcp** [comment]
I will stop force-pushing on next now, so it's safe to pull. But I think there is some debugging to do.

**Comment by marcocalignano** [comment]
All the sgf files contain only the first move, even if genmove works because we can output the move but somehow it is not registered in the game log.

**Comment by marcocalignano** [comment]
I might have found the problem testing now ...

**Comment by marcocalignano** [comment]
Game data d7b53e2eb316153e5ef48e4ba79161e3267c1aaf82d3ede20348bd7f0319af5b stored in database

Game data 7f000e0562e794b2a6f1eb0a086613f9595d5ebfcf7d9162910bb8736d74a58c stored in database

Can you check these?

**Comment by gcp** [comment]
They are both short and have the exact same result.

(PS. It's better to just disable the curl submission of these broken results, and comment out the code that deletes the files, then you can check locally)

In leela's commandline, you can use loadsgf file.sgf and then do commands like "final_score" etc.

**Comment by marcocalignano** [comment]
In my test seems everything OK I try to upload a couple of file so you can check them

**Comment by marcocalignano** [comment]
Game data 67d76c833387c739da910f722b30d2380fd400d540464d786f1f135aace6bed1 stored in database

Game data 3e8cbddb8febea86880e5e282eaf58a2046c3f6110af25aea1922d1d91e15c89 stored in database

Check these please.

**Comment by marcocalignano** [comment]
I checked them I would like only a second opinion!

**Pull request merged**
