### PR TITLE
Building for Mac OS X updated

### PR DESCRIPTION
**Pull request by toomasr**
I went through the Mac part today and had to brew install zlib and qt5 also to make cmake happy. I've added these two to the list.

### CODE REVIEW

**Comment by wonderingabout** [comment]
my pull request is related to yours : https://github.com/gcp/leela-zero/pull/2071

see mac building instructions

**Comment by wonderingabout** [comment]
however as you can see in @gcp 's review, qt5 should be installed only if one person wants to contribute,

therefore it should be an optionnal step

**Comment by wonderingabout** [comment]
is zlib needed for autogtp or for cmake ?

**Comment by gcp** [comment]
>is zlib needed for autogtp or for cmake ?

zlib is needed for Leela itself, to decompress weights files on the fly.

I pulled the zlib part only, qt5 is not required as you explained.

**Pull request closed without merging**
