### PR TITLE
OS auto detection for leelaz compile

### PR DESCRIPTION
**Pull request by bood**
So you don't have to do extra modifications when compiling on MacOS

### CODE REVIEW

**Comment by gcp** [comment]
Seems fine but can you actually get a working Windows version out of the Makefile? If everyone uses the MSVC project files then we don't need that part.

**Comment by bood** [comment]
Makefile on windows is tricky. MSVC has some support thru NMAKE but making a single makefile working with both GNU make and NMAKE could be not that pleasant.

Better approach is probably use `CMake` (noticing there are already some cmake files in the repo, deprecated?). I can look into that some time later.

**Comment by gcp** [comment]
Then I'd suggest stripping the OS_WIN part out and I'll pull.

**Comment by bood** [comment]
Fair enough. Just removed.

**Pull request merged**
