### PR TITLE
Set resignpct=10 in 90% of autogtp games

### PR DESCRIPTION
**Pull request by killerducky**
The first two commits just add resign_analysis.py and make changes to autogtp and leela src to support analyzing what the resign threshold should be. The last commit actually implements resignpct=10 in 90% of autogtp games. This should be pretty conservative because stats show there are only 2.13% incorrect resigns with this threshold, and we still get a 42% reduction in game length.

I wasn't sure how I should be generating random numbers, certainly the code I have in now is bad because it doesn't initialize the seed. Can someone show how I should do it? 

Here are the statistics using the latest net (22373747):
```
Resign rate: 0.50
Black won 467/516 (90.50%)
Incorrect uct resigns = 46/516 (8.91%)
Average game length = 285. Average game length with resigns = 2 (99.30% reduction)

Resign rate: 0.20
Black won 467/516 (90.50%)
Incorrect uct resigns = 18/516 (3.49%)
Average game length = 285. Average game length with resigns = 128 (55.00% reduction)

Resign rate: 0.15
Black won 467/516 (90.50%)
Incorrect uct resigns = 14/516 (2.71%)
Average game length = 285. Average game length with resigns = 147 (48.37% reduction)

Resign rate: 0.10
Black won 467/516 (90.50%)
Incorrect uct resigns = 11/516 (2.13%)
Average game length = 285. Average game length with resigns = 166 (41.77% reduction)

Resign rate: 0.05
Black won 467/516 (90.50%)
Incorrect uct resigns = 8/516 (1.55%)
Average game length = 285. Average game length with resigns = 193 (32.25% reduction)
```

### CODE REVIEW

**Comment by killerducky** [comment]
Here is how the flow works for analyzing the resign threshold. For now I propose someone just run this flow every so often to make sure the threshold is still good.

```
./resign_analysis.py -h
usage: resign_analysis.py [-h] [--r Resign rates] [--v Verbose] files [files ...]

This script analyzes the debug output from leelaz
to determine the impact of various resign thresholds.

Process flow:
  Run autogtp with debug on:
    autogtp -k savedir -d savedir

  Unzip training and debug files:
    gunzip savedir/*.gz

  Analyze results with this script:
    ./resign_analysis.py savedir/*.txt.debug.0

Note the script takes the debug files hash.txt.debug.0
as the input arguments, but it also expects the training
files hash.txt.0 to be in the same directory.

positional arguments:
  files             Debug data files (*.txt.debug.0)

optional arguments:
  -h, --help        show this help message and exit
  --r Resign rates  comma separated resign thresholds (default 0.5,0.2,0.15,0.1,0.05)
  --v Verbose

```

**Comment by gcp** [comment]
I think we should generate statistics on multiple nets, or else pick a more conservative parameter set (5% in 80% of the games?). Else there seems to be some risk that they are suitable for 22373747 and friends but not for the next few nets, and we can't update this easily. This is especially true with the very lopsided black favored results.

**Comment by isty2e** [comment]
@gcp Probably it would be safe to be conservative indeed, but regarding the update, if things mentioned in [here](https://github.com/gcp/leela-zero/issues/153) are implemented (hope it won't take too long) such parameters can be easily configurable on the server, I guess.

**Comment by gcp** [comment]
Ok. I think I'll take the conservative ones, do a release, and we can make things dynamic in the next client/server iteration.

**Comment by gcp** [comment]
Can you try rebasing this? My commit above should have the correct random number stuff.

**Comment by killerducky** [comment]
rebase done.

I also tested autogtp with upload enabled for the first time (previous resign testing I disabled the upload code). Things look ok from my end.

```
autogtp v5
Best network hash: 6f274ab150b9c79a341cce67c97b9116a6fcf3b1a8c9a613f6f7a6709658750f
Required client version: 4 (OK)
Already downloaded network.
option= -r 5 -g -q -d -n -m 30 -w 
Engine has started.
Infinite thinking time set.
1 (F19) 2 (P8) 3 (Q6) 4 (S13) 5 (D2) 6 (N2) 7 (P7) 8 (K12) 9 (N18) 10 (C11) 11 (O12) 12 (H9) 13 (H10) 14 (B4) 15 (R10) 16 (B9) 17 (G11) 18 (C9) 19 (O11) 20 (E8) 21 (Q11) 22 (J12) 23 (J2) 24 (N4) 25 (Q19) 26 (B10) 27 (D5) 28 (J18) 29 (O8) 30 (K2) 31 (L9) 32 (Q7) 33 (O7) 34 (L3) 35 (J6) 36 (M17) 37 (F17) 38 (D13) 39 (K5) 40 (pass) 41 (J3) 42 (F18) 43 (G18) 44 (G10) 45 (H12) 46 (G9) 47 (H16) 48 (F16) 49 (J9) 50 (E17) 51 (J17) 52 (J14) 53 (E16) 54 (K13) 55 (N11) 56 (J11) 57 (H11) 58 (J10) 59 (M10) 60 (G8) 61 (R14) 62 (J16) 63 (E18) 64 (P4) 65 (M14) 66 (P14) 67 (D17) 68 (C6) 69 (J15) 70 (M16) 71 (H3) 72 (S9) 73 (L6) 74 (E13) 75 (H17) 76 (C5) 77 (F12) 78 (S14) 79 (G2) 80 (R13) 81 (Q8) 82 (P16) 83 (N16) 84 (L2) 85 (M15) 86 (Q16) 87 (O4) 88 (L7) 89 (F3) 90 (K15) 91 (R4) 92 (O3) 93 (N15) 94 (R8) 95 (R7) 96 (H13) 97 (F14) 98 (O5) 99 (R9) 100 (C14) 101 (F13) 102 (Q4) 103 (K16) 104 (S8) 105 (N17) 106 (E10) 107 (S10) 108 (E12) 109 (M13) 110 (H6) 111 (H5) 112 (G6) 113 (M18) 114 (P1) 115 (R5) 116 (resign) Game has ended.
Winner: black
Writing 4bf5fe3f5c044d8794aa7cdbbfe37316.sgf
Dumping 4bf5fe3f5c044d8794aa7cdbbfe37316.txt
1 game(s) played in 1 minutes = 80 seconds/game, last game took 80 seconds.
curl -F networkhash=6f274ab150b9c79a341cce67c97b9116a6fcf3b1a8c9a613f6f7a6709658750f -F clientversion=5 -F sgf=@4bf5fe3f5c044d8794aa7cdbbfe37316.sgf.gz -F trainingdata=@4bf5fe3f5c044d8794aa7cdbbfe37316.txt.0.gz http://zero.sjeng.org/submit
Game data 565633ff3d2d85432bf34b2f99dd113ecad9e32380fd622155a24e204dc09f81 stored in database

```

**Comment by gcp** [comment]
Ugh, I fixed the random number generation part, and referred to it, but github made it disappear when you rebased....

**Comment by killerducky** [comment]
Oh sorry I must have messed up with I fixed the merge conflict. Let me see if I can fix it.

**Comment by killerducky** [comment]
Fixed.

**Comment by killerducky** [comment]
New data for 595k (6f274ab1). Looks like we are still safe.

```
Resign rate: 0.50
Black won 198/206 (96.12%)
Incorrect uct resigns = 8/206 (3.88%)
Average game length = 216. Average game length with resigns = 2 (99.08% reduction)

Resign rate: 0.20
Black won 198/206 (96.12%)
Incorrect uct resigns = 7/206 (3.40%)
Average game length = 216. Average game length with resigns = 11 (94.72% reduction)

Resign rate: 0.15
Black won 198/206 (96.12%)
Incorrect uct resigns = 2/206 (0.97%)
Average game length = 216. Average game length with resigns = 65 (69.76% reduction)

Resign rate: 0.10
Black won 198/206 (96.12%)
Incorrect uct resigns = 1/206 (0.49%)
Average game length = 216. Average game length with resigns = 143 (33.57% reduction)

Resign rate: 0.05
Black won 198/206 (96.12%)
Incorrect uct resigns = 0/206 (0.00%)
Average game length = 216. Average game length with resigns = 183 (15.25% reduction)
```

**Pull request merged**
