### PR TITLE
validation: adding Stop Resume feature

### PR DESCRIPTION
**Pull request by marcocalignano**
This will save the results and Sprt data. This won't save the running games.

### CODE REVIEW

**Comment by marcocalignano** [comment]
@zediir Yes! This is all for you :smiley:

**Comment by WhiteHalmos** [comment]
Thank you! This will be very useful.

**Comment by WhiteHalmos** [comment]
By the way, a suggestion, can intermediate results be printed in a nice format after each game rather than just at the end of validation? Would `m_results.printResults(m_firstNet, m_secondNet);` work when status is `Sprt::Continue`?

**Comment by marcocalignano** [comment]
It works but wouldn't be verbose especially if you have more than one thread?

**Comment by WhiteHalmos** [comment]
True... perhaps when the games are stopped and resumed it would be a good time to output intermediate results? That way validation doesn't have to run till the end to have nice results available on demand?

Question: How does stop work? Does it respond to Ctrl+C?

**Comment by marcocalignano** [comment]
The stop funcion is the same like autogtp ```q+Enter```. And it prints the result when it is resumed. I need to add it when it stops. Give me a few mins.

**Comment by marcocalignano** [comment]
@WhiteHalmos Ok now you see the print out when you stop it and when you resume it.

**Comment by WhiteHalmos** [comment]
Thank you very much!

**Comment by marcocalignano** [comment]
@gcp When you merge this I have another PR ready. Using QLockFiles while loading saved files or uploading games.

**Comment by marcocalignano** [comment]
Or should I just add the commit here?

**Comment by gcp** [comment]
I prefer multiple small pulls. If I have a remark on one part it won't block the other parts.

(Maybe less applicable to autogtp/validation as you're de facto the maintainer for those)

**Pull request merged**
