### PR TITLE
Minor changes to VS2017 solution

### PR DESCRIPTION
**Pull request by qysnn**
I made some changes to the solution setting so that the it will work out of the box with VS2017. I also updated the solution so that it works with recent updates of next branch and fixed a bug that causes crash on Windows. But unfortunately I failed to make the solution automatically add dependencies to output dir as @earthengine did. So you will need to add them manually. 
Tested on Windows 10 and Ubuntu 16.04

### CODE REVIEW

**Comment by zediir** [comment]
Thanks. This one works for me. Current next gives me the error "error MSB6006: "cmd.exe" exited with code 1"

**Comment by zediir** [comment]
I get this error when I try to build it

autogtperror

**Comment by qysnn** [comment]
@zediir I would suggest you to update with the newest commits and try to debug within Visual Studio so that you will have a better track of what's going wrong.

**Comment by zediir** [comment]
Yeah no idea what happened. I changed the project qt version to msvc2017_64 and it worked and then changed it back to $(DefaultQtVersion) and it works again.

**Comment by gcp** [comment]
@earthengine can you take a look?

**Comment by earthengine** [comment]
I think this should be good, except that there should be some changes in the VC2015 solution as well.

**Comment by qysnn** [comment]
@earthengine Thank you for your review. 
I switch it to Windows SDK 10 because it is the default SDK if you install VS2017, Windows SDK 8.1 will not be installed by default.
I also noticed that Qt is not using QtDll but I didn't change anything about it. It is the default behaviour I guess.

**Comment by gcp** [comment]
I pulled the other request which I believe included this.

**Pull request closed without merging**
