### PR TITLE
An improved implementation of #1514 (screening out low net score children)

### PR DESCRIPTION
**Pull request by Splee99**
To recap the issue #1514, LZ sometimes plays weird first line or second line move when win rate is low. All those moves have one thing in common, low net scores. In this implementation those low score children will not be selected and other better moves will get more visits instead.
The ELF weight with only one playout is the best tester for this. The original LZ 0.15 often plays many weird moves in 5 handicap games and is unable to win ELF 1 playout with 3000 playouts. With the modified version LZ won many of the games. One example is here:
[elf1-5h-e1d4-3000po-cap-only1.sgf.txt](https://github.com/gcp/leela-zero/files/2195329/elf1-5h-e1d4-3000po-cap-only1.sgf.txt)

### CODE REVIEW

**Comment by gcp** [comment]
Not going to pull in a change that ass a random magic parameter, nor that breaks the search scaling by making it unable to find good moves with low priors.

This will never be pulled.

**Comment by alreadydone** [comment]
@Splee99 I haven't had time to try your modification yet, but I ran 9 games with my komi-v0.3 (3000 playouts, some with different parameters) against ELF 1 playout, and komi-v0.3 won only one game due to ladder, so your claim indeed sounds impressive. Will you keep testing and collect data and also test against humans? By the way, you can do such pruning at the time of creating children, but with a different metric: not the net score itself, but the ratio between the net score and the highest net score.
https://github.com/gcp/leela-zero/blob/8e9ca8eb073632141b3c4995f389fc9c481f3d67/src/UCTSearch.cpp#L207-L208
https://github.com/gcp/leela-zero/blob/8e9ca8eb073632141b3c4995f389fc9c481f3d67/src/UCTNodeRoot.cpp#L186
So you can change get_min_psa_ratio() to a fixed value like you did in this PR (or add it to the end in the second case). This should save some memory and computation but the gain is probably minor.

**Comment by Splee99** [comment]
@alreadydone With this modification only LZ still plays weird first line or second line move. Then I changed cfg_puct from 0,8 to 0,2, those weird moves are completely gone and LZ can win ELF 1 playout with 2700 playouts.
[elf1-5h-e1d4-2700po-cap-0.9-puct0.2.sgf.txt](https://github.com/gcp/leela-zero/files/2199770/elf1-5h-e1d4-2700po-cap-0.9-puct0.2.sgf.txt)
I don't care this change will be ignored. I'll keep it for myself.

**Comment by alreadydone** [comment]
Despite your tests, I find it highly suspicious that changing 0.8 to 0.2 would help avoid 1st/2nd line moves. This PR is filtering out low net score moves, while shrinking cfg_puct would make search focus more on winrate (which is not reliable when it's very low) and not policy prior. So the two changes seem to work against each other.

**Pull request closed without merging**
