### PR TITLE
Check the network file hash

### LINKED ISSUE #128: client didn't check the checksum of network file
If the download of value network file is incomplete, the client will quit immediately after start engine. 
There is no check or retry for the network file. Every time you execute the client, it will fail.

### PR DESCRIPTION
**Pull request by Ttl**
Uses picosha2 (https://github.com/okdshin/PicoSHA2) for generating the hash.

Fixes #128

### CODE REVIEW

**Comment by gcp** [comment]
FWIW Qt also has support for this http://doc.qt.io/qt-5/qcryptographichash.html

That said no objection over adding a single MIT licensed header-only lib.

**Comment by marcocalignano** [comment]
That won't 'ruin' GPL 3?

**Comment by Ttl** [comment]
I'll redo this with the Qt function. Just a sec.

**Comment by Ttl** [comment]
I updated the commit.

**Comment by gcp** [comment]
MIT and X11 license are compatible with GPLv3. There is already other MIT/X11 code in the tree.

**Comment by marcocalignano** [comment]
On line 187 of Production.cpp, can't you delete the file and return false so the network is downloaded again?
I think is better then exiting

**Comment by Ttl** [comment]
If that check fails there are some serious problems. If the file can't be opened for reading I'm not so sure that deleting it is going to succeed either.

**Comment by marcocalignano** [comment]
so if QFileInfo::exists finds it but cannot open for reading, probably we miss permission so we cannot even delete it but you can still try and of deleting fail you can exit. (maybe)

**Pull request merged**
