### PR TITLE
truncate to 4 precision and compress converted minigo weights.

### PR DESCRIPTION
**Pull request by sethtroisi**

### CODE REVIEW

**Comment by l1t1** [comment]
7-zip's gz format is about 90% size of gzip, and @gcp uses it. pls use it so

**Comment by sethtroisi** [comment]
I would be very supervised by that result.

I spot checked a single file

|tool|final_size|compression_ratio|
|----|----|-----|
|raw|229mb|1.0|
|gzip (this code) l=9|64mb|28%|
|gzip l=7|72mb|31% (but much faster)|
|7z a test.txt.gz|61mb|27%|

**Comment by l1t1** [comment]
compress ratio is related with  precision, 3 is higher, 2 even higer, iuse mx5 in7z

**Comment by gcp** [comment]
>iuse mx5

This was worse for me than mx9, so the official networks still use that.

**Pull request merged**
