### PR TITLE
Tensor Core support with PTX inline assembly

### PR DESCRIPTION
**Pull request by ihavnoid**
See #2036 for details.  ~10% performance gain on a V100 cluster.  Validated that doesn't lose strength on equal playout (vs. current next branch)

### CODE REVIEW

**Comment by gcp** [comment]
@ihavnoid is this solid enough to pull?

Does @Ttl perhaps want to help reviewing?

**Comment by Ttl** [comment]
I don't have GPU with tensor cores so I can't test this, but looking at the code I don't really see any issues.

**Comment by ihavnoid** [comment]
I think the code itself is okay, but after second thought I think we can wait until we have the cuda implementation so that we can skip merging this if cuda performs much better than this.  I think there is no need to hurry merging, it's not like there are other outstanding branches that might conflict a lot (or... do we?)

Biggest concern I have is that I tested this only on a v100 in Google cloud.

**Comment by gcp** [comment]
>Biggest concern I have is that I tested this only on a v100 in Google cloud.

From what I understand, the optimal use of Tensor Cores on RTX (compute capability 7.5) devices is different from that on 7.0 devices, due to the Tensor Core vs CUDA ratio. I'm not sure if this has any effect on your code.

But it could be seen in some benchmarks of the RTX cards, where SGEMM benchmark kernels did not get the expected speed on the RTX cards because they weren't compiled with 7.5 support.

**Comment by jpturcotte** [comment]
If that could help, I would be ready to test this on a desktop with a RTX 2070. I could also test the CUDA backend, but I would need help to set all this up. I can setup Git and MSVC, but I am not sure what to do after that.

**Comment by gcp** [comment]
First observation: we are only checking one specific instruction to see whether it's supported: 4fc611335a36f4648997806ce14cadd111185385

But the tuner selects:

(363/380) KWG=16 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=32 NDIMC=32 NWG=32 SA=0 SB=0 STRM=0 STRN=0 TC E=1 VWM=2 VWN=2 0.0236 ms (5008.7 GFLOPS)

Which seems inconsistent with https://github.com/gcp/leela-zero/pull/2049/files#diff-248059ab88d371db2d8ef2fe42733d7cR84

**Comment by gcp** [comment]
Hmm, I guess that is working as intended and indicates that this card does support them. We report TC support as soon as any of the instructions work, and then filter in the tuner.

**Comment by gcp** [comment]
Factory clocked RTX 2080, benchmark with ffe8ba44.

next:
4t = 408
8t = 446
16t = 560

tensorcores:
4t = 507
8t = 579
16t = 549

Tuner goes from 3 TFLOPS to 5 TFLOPS.

Seems good enough to pull, even if we're clearly having some bottleneck elsewhere.

**Comment by lp200** [comment]
I hope ihavnoid/batch-full branch will be merged
It shows great performance with tensor core.

V100 256x20 net

-t 16  batch 5
 6400 evaluations in  2.11 seconds -> 3039 n/s

-t 32 batch 12
 6400 evaluations in  1.57 seconds -> 4085 n/s

**Comment by ihavnoid** [comment]
> Hmm, I guess that is working as intended and indicates that this card does support them. We report TC support as soon as any of the instructions work, and then filter in the tuner.

Yes correct.  There seems to be some GPUs that only support m16n16k16 format while others support more formats.  Testing all three fails to pick up those GPUs.

**Comment by ihavnoid** [comment]
> I hope ihavnoid/batch-full branch will be merged
> It shows great performance with tensor core.
> 
> V100 256x20 net
> 
> -t 16 batch 5
> 6400 evaluations in 2.11 seconds -> 3039 n/s
> 
> -t 32 batch 12
> 6400 evaluations in 1.57 seconds -> 4085 n/s

I'll work on a cleanup.  Currently it merge-conflicts on various places.

**Pull request merged**
