### PR TITLE
update quantize_weights.py with round  some numbers to 2 digits  reduce weight file size

### PR DESCRIPTION
**Pull request by l1t1**
see https://github.com/gcp/leela-zero/issues/2107#issuecomment-451390081

### CODE REVIEW

**Comment by gcp** [comment]
@Ttl any thoughts? Looks pretty safe to me?

**Comment by Ttl** [comment]
Yes, this looks safe.

**Comment by gjm11** [comment]
Why is this worth doing? I mean, it makes the weight files a little smaller, and it presumably may make the networks a little weaker. On what grounds is this thought to be a good tradeoff? In the discussion of #2107 I see some evaluations of e.g. the L2 norm of the difference in the weight vectors (which I guess is useful for finding big errors but tells us nothing about the impact on how well the network chooses or evaluates moves) and nothing that, e.g., plays more-quantized against less-quantized networks, or compares their move choices or win probability estimates.

What's the need for this? Why has it been committed without any evaluation of anything relevant to actual go-playing performance?

**Comment by wonderingabout** [comment]
@gjm11 

i agree with you, i see little benefit to compress further

this is likely to do more harm than good

**Comment by gcp** [comment]
Mostly because it makes sense and it's similar to trellis quantization. I didn't pay enough attention to the error bound in here though: our current quantization to 3 digits should suggest a bound like <0.005, not 0.01 which is 2 digits!

You are right this shouldn't be have been enabled without testing, and I'm going to back it out.

**Comment by l1t1** [comment]
362,149,606 199.txt
346,808,778 199_quantized(err<0.005).txt
331,955,103 199_quantized(err<0.01).txt

**Comment by l1t1** [comment]
i saw words such as likely and should. i didnt see an  evidence of it weaken the orignal weight.
recent ten matchs winrate are not bigger than  0.5, only one is quantized by the pr. 
pls give it a chance to have more tests.

**Comment by l1t1** [comment]
some candidates maybe the quantized version of
1. current best lz201
2. the one has biggest winrate to lz201 ,ie. c3ed2789
3. each long steps new weights,ie +128 +192 +256

**Pull request merged**
