### PR TITLE
#697 Add a high level comment on the GTP class. Also give a web refer…

### PR DESCRIPTION
**Pull request by barrybecker4**
I followed @wctgit  suggestion and just added a comment and web reference. No code changes.

### CODE REVIEW

**Comment by killerducky** [comment]
Your commit log message is all on one line. I think this can happen if you do not leave the 2nd line blank.

**Comment by barrybecker4** [comment]
I don't think I can amend it because it's already pushed to the branch. Is it bad to have it all on once line?
 Are there certain conventions that need to be followed?

**Comment by killerducky** [comment]
You can do a force push, or just let gcp fix it. 

Check this for some guidelines:
https://github.com/erlang/otp/wiki/writing-good-commit-messages

**Comment by gcp** [comment]
>I don't think I can amend it because it's already pushed to the branch

git push -f

**Pull request merged**
