### PR TITLE
Update autogtp README.md with apt install command

### PR DESCRIPTION
**Pull request by sethtroisi**
Updated Requirements:
QRegularExpression requires Qt5,  https://github.com/vaibhavpandeyvpz/apkstudio/issues/10

### CODE REVIEW

**Comment by sethtroisi** [comment]
gcp, I modified to use the "qmake -qt5" per https://github.com/gcp/leela-zero/issues/66, alternatively I can try to do #ifdef on which qt version is present.

**Comment by gcp** [comment]
I did a check and QStringLiteral is also Qt5 only, so I guess Qt4 isn't really supported any more.

**Comment by pmontrasio** [comment]
`sudo apt install qt5-default` didn't make it into the README of the autogtp directory on the main branch yet. This could stop some people from compiling and running autogtp.

**Comment by gcp** [comment]
Is qt5-default needed if you give the correct qmake command?

**Comment by sethtroisi** [comment]
qt5-default causes qtbase5-dev to be installed which is what's actually satisfying the but one of them is still needed

**Pull request merged**
