### PR TITLE
autogtp: fixing default value for any boolean option

### PR DESCRIPTION
**Pull request by marcocalignano**
This fixes the problem with 'noise : false'

### CODE REVIEW

**Comment by roy7** [comment]
I was concerned about storing booleans in the database as "false" native boolean since what if it turned into 0 or something, so I do cast it to a String internally all of the time.

**Comment by marcocalignano** [comment]
@roy7 so what would you like to have?

**Comment by roy7** [comment]
My C++ skills are weak, I have no idea, I'm just letting you know I pass options.noise as a String per our discussion that you want all options as strings. :)

**Comment by marcocalignano** [comment]
@roy7 yes the type is string but the string content you can choose :smile:

**Comment by marcocalignano** [comment]
@roy you could save it as a string in the DB?

**Comment by roy7** [comment]
I do save it as a string. :)

**Comment by bood** [comment]
It seems a bit odd to me that you use all values as string types.
IMO bool/number types are better choice when the options are bool/numbers.

**Comment by gcp** [comment]
C++ doesn't support JSON at all, he's "lucky" that Qt has support classes for it :-)

**Comment by bood** [comment]
No easy library either? (Probably not with reflection)

But in general, I think we can still learn something from java.

I would suggest write a class representing the whole `json` object and fill it with the json received. Then just manipulate the `leelaz` options according to the class filled earlier. Could make the code cleaner maybe? It's up to you though :-) @marcocalignano

**Pull request merged**
